const kontributorData = [
  {
    id: 1,
    name: "Moh. Rasyid Siddiq",
    nim: "F52123069",
    instagram: "null",
    username_linkedin: "putri-innayah",
    linkedin: "",
    image: "/aset/man.jpg",
  },
  {
    id: 2,
    name: "Sitti Cahya Ramadani",
    nim: "F52123070",
    instagram: "null",
    username_linkedin: "asep-permadi",
    linkedin: "",
    image: "/aset/woman.jpg",
  },
  {
    id: 3,
    name: "Nadhia Putri Aprhilia",
    nim: "F52123071",
    instagram: "null",
    username_linkedin: "hijra-s-otji",
    linkedin: "",
    image: "/aset/woman.jpg",
  },
  {
    id: 4,
    name: "Fachriadi",
    nim: "F52123077",
    instagram: "null",
    username_linkedin: "null",
    linkedin: "",
    image: "/aset/man.jpg",
  },
  {
    id: 5,
    name: "Dinar Fauziah",
    nim: "F52123078",
    instagram: "@null",
    username_linkedin: "null",
    linkedin: "",
    image: "/aset/woman.jpg",
  },
  {
    id: 6,
    name: "Edgar",
    nim: "F52123082",
    instagram: "@null",
    username_linkedin: "",
    linkedin: "",
    image: "/aset/man.jpg",
  },
  {
    id: 7,
    name: "Safana Annisa Salsabilah",
    nim: "F52123083",
    instagram: "@null",
    username_linkedin: "null",
    linkedin: "",
    image: "/aset/woman.jpg",
  },
  {
    id: 8,
    name: "Yesenia Tracy Nitha Salluk",
    nim: "F52123087",
    instagram: "@null",
    username_linkedin: "null",
    linkedin: "",
    image: "/aset/woman.jpg",
  },
  {
    id: 9,
    name: "Muh. Azhar Rasyid",
    nim: "F52123089",
    instagram: "@null",
    username_linkedin: "null",
    linkedin: "",
    image: "/aset/man.jpg",
  },
  {
    id: 10,
    name: "Joshua Riman Kape",
    nim: "F52123092",
    instagram: "@null",
    username_linkedin: "null",
    linkedin: "",
    image: "/aset/man.jpg",
  },
  {
    id: 11,
    name: "Rifky Harun",
    nim: "F52123094",
    instagram: "@null",
    username_linkedin: "null",
    linkedin: "",
    image: "/aset/man.jpg",
  },
  {
    id: 12,
    name: "Muh. Yusuf",
    nim: "F52123095",
    instagram: "@null",
    username_linkedin: "null",
    linkedin: "",
    image: "/aset/man.jpg",
  },
  {
    id: 13,
    name: "Kadek Surya Adi Dwi Putra",
    nim: "F52123099",
    instagram: "@null",
    username_linkedin: "",
    linkedin: "",
    image: "/aset/man.jpg",
  },
  {
    id: 14,
    name: "Moh. Afizan",
    nim: "F52121020",
    instagram: "@moh_afizan",
    username_linkedin: "moh-afizan",
    linkedin: "https://www.linkedin.com/in/moh-afizan/",
    image: "/aset/man.jpg",
  },
];

export default kontributorData;
